default_platform(:ios)

platform :ios do
  # 
  lane :test do 
    sh("cd .. && xcodebuild -resolvePackageDependencies -scheme TCA_Sample")

    scan(
      scheme: "./TCA_Sample",
      device: "iPhone 17",
      xcargs: "-skipMacroValidation"   # TCA マクロエラー防止
    )
  end
end